; Exercise 1.9:
; Using the substitution model, illustrate the process generated by
; each procedure in evaluating (+ 4 5). Are these processes iterative
; or recursive?

(define (inc n)
  (+ n 1))

(define (dec n)
  (- n 1))

(define (add_rec a b)
  (if (= a 0) 
	b 
	(inc (+ (dec a) b))))

(define (add_inc a b)
  (if (= a 0) 
	b 
	(+ (dec a) (inc b))))


; The first process is recursive:
(add_rec 4 5)
; (inc (+ (dec 4) 5))
; (inc (+ 3 5))
; (inc (inc (+ (dec 3) 5)))
; (inc (inc (+ 2 5)))
; (inc (inc (inc (+ (dec 2) 5))))
; (inc (inc (inc (+ 1 5))))
; (inc (inc (inc (inc (+ (dec 1) 5)))))
; (inc (inc (inc (inc (+ 0 5)))))
; (inc (inc (inc (inc 5))))
; (inc (inc (inc 6)))
; (inc (inc 7))
; (inc 8)
; 9

; The second process is iterative
(add_inc 4 5)
; (+ (dec 4) (inc 5)) --> (add_inc 3 6)
; (+ (dec 3) (inc 6)) --> (add_inc 2 7)
; (+ (dec 2) (inc 7)) --> (add_inc 1 8)
; (+ (dec 1) (inc 8)) --> (add_inc 0 9)
; 9
