; Exercise 1.15:
; The sine of an angle (radians) can be computed by making use of
; the approximation sin(x) ~ x if x is sufficiently small, and the
; trigonometric identity

; sin(x) = 3*sin(x/3) - 4*sin^3(x/3)

(define (cube x) 
  (* x x x))

(define (p x) 
  ; the following gets executed when x < 0.1
  (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
  (if (not (> (abs angle) 0.1))
	angle
	(p (sine (/ angle 3.0)))))

; (a) How many times is the procedure p applied when (sine 12.15) 
; is evaluated?

(sine 12.15)
; (p (sine 4.05))
; (p (p (sine 1.35)))
; (p (p (p (sine 0.45))))
; (p (p (p (p (sine 0.15)))))
; (p (p (p (p (p (sine 0.05)))))) --> 0.05 < 0.1
; (p (p (p (p 0.1495))))
; (p (p (p 0.435)))
; (p (p (0.975)))
; (p -0.789)
; ---> -0.399

; p gets called 5 times; that is, until angle < 0.1.


; (b) What is the order of growth in space and number of steps 
; (as function of a) used by the process generated by the sine
; procedure when (sine a) is evaluated?

; tbh I had to to a bit of research here:
; We can see that angle is divided by 3.0 each time p is called.
; Therefore, we can say that the number of steps will vary
; logarithmically wih x, so the complexity is O(log(x)). 
; The same can be applied for growth in space.

